# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron Smith
tagline:          'Thoughts on Tech'
description:      'Opinions on machine learning, AI, and my work in technology.'
url:              http://aaronhsmith.com
paginate:         1
baseurl:          /
author:
  name:           Aaron Smith
  url:            https://twitter.com/dblarons
  email:          aaronsmith.dev@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dblarons

# For header
pages_list:
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'
    Contact: 'mailto:aaronsmith.dev@gmail.com'
